apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-gpu-agent-config
  namespace: logging-and-monitoring
data:
  agent.yaml: |
    metrics:
      global:
        scrape_interval: 60s
      configs:
        - name: default
          scrape_configs:
            - job_name: 'dcgm-stats'
              static_configs:
                - targets: ['nvidia-dcgm-exporter.nvidia.svc.cluster.local:9400']
          remote_write:
            - url: https://prometheus-prod-56-prod-us-east-2.grafana.net/api/prom/push
              basic_auth:
                username: <path:secret/data/grafana-alloy-monitoring-metrics-username#value>
                password: <path:secret/data/grafana-alloy-monitoring-metrics-password#value>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-gpu-agent
  namespace: logging-and-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-gpu-agent
  template:
    metadata:
      labels:
        app: grafana-gpu-agent
    spec:
      containers:
      - name: agent
        image: grafana/agent:v0.40.3
        args:
          - "--config.file=/etc/agent/agent.yaml"
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        volumeMounts:
          - name: config
            mountPath: /etc/agent
      volumes:
        - name: config
          configMap:
            name: grafana-gpu-agent-config